### PR TITLE
Netty 4.1.0.Final release

### PR DESCRIPTION
**Pull request by yschimke**

### CODE REVIEW

**Comment by stevegury** [comment]
I overheard @rdegnan talking with @NiteshKant about something that prevented us to upgrade.
Could you guys confirm?

**Comment by yschimke** [comment]
No rush from me, I was playing around with the http2 codec and wanted to be on the final release.  it would be good to have an issue in this project or Netty to track the fix needed.

**Comment by NiteshKant** [comment]
The issue was that RxNetty was(is) not upgraded to the latest netty artifacts. I have a PR for the upgrade but haven't yet merged & released.

**Comment by yschimke** [comment]
Closing, as the change to pull in a new RxNetty should bump these versions.

**Pull request closed without merging**
