### PR TITLE
Added udt support

### PR DESCRIPTION
**Pull request by rdegnan**

### CODE REVIEW

**Comment by stevegury** [comment]
Don't take it personnaly, but unless we plan to use UDT, and I don't think we do, we shouldn't slow ourselves with maintenance cost of extra code.
If you want to add support for UDT, what about having another repo called `reactivesocket-contrib` where we put contributions that are not actively mainetained/use by us.

**Comment by NiteshKant** [comment]
@stevegury 👍 on separating experimental(not actively used) modules from the mainstream modules. 
Since we are on the topic of names; I would put my vote for `reactivesocket-experimental` or `reactivesocket-skunkworks` 😄

**Comment by rdegnan** [comment]
I think the netty implementations are so similar it does make sense to group them together, or at least have a reactivesocket-netty-common project in addition to the individual modules -- it's really only the channel setup that differs per protocol. We should try to find the proper abstraction so that we can share code as much as possible. Netty doesn't support that many protocols out of the box that are suitable for reactivesocket, the only other one I think is interesting is SCTP, so the number of modules wouldn't be that large.

**Comment by stevegury** [comment]
Closing, this repo will die in favor of reactivesocket-java.

**Pull request closed without merging**
