### PR TITLE
Custom CBOR codec (for metadata)

### PR DESCRIPTION
**Pull request by NiteshKant**
For default metadata mime-type, using Jackson CBOR codec, produces more allocations (one buffer allocation per value) which are unnecessary. This was the major driving factor to invest in a _simple_ codec that can reduce allocations and be more suitable for ReactiveSocket design (using thread-local pooled buffers).

Although, the codec is intended to be used only for a map type, but it is rather generic to be used for a majority of CBOR data types. If this proves useful, we can extend this for the remaining data types.

### CODE REVIEW

**Comment by NiteshKant** [comment]
\cc @stevegury @robertroeser

**Comment by stevegury** [comment]
I didn't verify the CBOR spec, but the code look alright.
👍

**Comment by NiteshKant** [comment]
Thanks @stevegury for the review. 

I have tests which encode with jackson and decode with this codec and vice-versa so I have good confidence that we are abiding by the spec.

**Comment by stevegury** [comment]
Just an idea: would it be possible to create random objects, that you serialize/deserialize with this library and deserialize/serialize with jackson, but only add a test dependency on jackson?

**Comment by NiteshKant** [comment]
The codec is not feature complete i.e. it does not serialize/deserialize all types of objects, which is the reason it can not completely replace jackson as of now and hence the compile dependency on Jackson.

**Comment by stevegury** [comment]
> The codec is not feature complete
I get that, I was implicitly proposing generating Maps of things that this can be serialized/deserialized by this library.

**Comment by NiteshKant** [comment]
Ok I think I got confused by the "only add a test dependency on jackson" part :)

So I have this type of tests for all type codecs: 

https://github.com/ReactiveSocket/reactivesocket-java-impl/blob/master/reactivesocket-mime-types/src/test/java/io/reactivesocket/mimetypes/internal/cbor/CborMapCodecTest.java#L63

Which does encode/decode with this codec and decode/encode with jackson. Is this roughly what you are saying?

**Comment by stevegury** [comment]
Yes.
If you only need jackson during the tests, a testCompile dependency should be sufficient.

**Pull request merged**
